name: "CI"

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  ci:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      # # Inject all environment variables from ".env.example" in $GITHUB_ENV
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          mode: example

      - name: "Install the dependencies"
        run: "yarn install --immutable --inline-builds"

      - name: "Lint solidity code"
        run: "yarn lint:sol"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Test the contracts"
        run: "yarn test:gas"

      - name: "Add test summary"
        run: |
          echo "## Test results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

      - name: "Generate the coverage report"
        run: "yarn coverage"

      - name: "Add coverage summary"
        run: |
          echo "## Coverage results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
