name: "CI"

env:
  DOTENV_CONFIG_PATH: "./.env.example"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  ### Run Linters ###
  lint:
    name: "Run Linters"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable --inline-builds"

      - name: "Lint the contracts"
        run: "yarn lint:sol"

      - name: "Add lint summary"
        run: |
          echo "## Lint results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  ### Build Contracts ###
  build:
    name: "Build Contracts"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable --inline-builds"

      - name: "Compile the contracts"
        run: |
          yarn clean
          yarn compile

      - name: "Add build summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  ### Run Tests ###
  test:
    name: "Run Tests"
    needs: ["lint", "build"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable --inline-builds"

      - name: "Run tests"
        run: "yarn test:gas"

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  ### Run Coverage ###
  coverage:
    name: "Run Coverage"
    needs: ["lint", "build", "test"]
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v3"

      - name: "Install Node.js"
        uses: "actions/setup-node@v3"
        with:
          cache: "yarn"
          node-version: "lts/*"

      - name: "Install the Node.js dependencies"
        run: "yarn install --immutable --inline-builds"

      - name: "Generate the coverage report"
        run: "yarn coverage"

      - name: "Add coverage summary"
        run: |
          echo "## Coverage results" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
